CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER(10,2),
    IsVIP VARCHAR2(5)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER(5,2),
    DueDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

INSERT INTO Customers VALUES (101, 'Ramesh', 65, 15000, 'FALSE');

INSERT INTO Customers VALUES (102, 'Sita', 45, 8000, 'FALSE');

INSERT INTO Customers VALUES (103, 'Rahul', 70, 20000, 'FALSE');

INSERT INTO Customers VALUES (104, 'Anita', 30, 12000, 'FALSE');

COMMIT;

INSERT INTO Loans VALUES
(1,101,10,TRUNC(SYSDATE)+20);

INSERT INTO Loans VALUES
(2,102,11,TRUNC(SYSDATE)+40);

INSERT INTO Loans VALUES
(3,103,9,TRUNC(SYSDATE)+10);

INSERT INTO Loans VALUES
(4,104,12,TRUNC(SYSDATE)+25);

COMMIT;

SELECT * FROM Customers;

SELECT * FROM Loans;